version: "1.0.0"
name: "picPay-users"
description: "end-to-end testing"
service:
  users:
    basePath: "https://gorest.co.in/public-api"
    token: "Bearer 2275e2cbbf8dc1d113b25fb018cdb2e07e088b35bb5f7b7c13ca160ed96a82ba"